In [1]:
import csv
from sqlalchemy import create_engine, MetaData
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
import pandas as pd
import os

In [2]:
# create mysql database connection
#engine = create_engine('mysql+pymysql://root:password@localhost:3306/birthrate_db', echo=False)
# create sqlite database connection
db_url = 'nat_birthrate_2013_2017.sqlite'
os.remove(db_url)
engine = create_engine(f'sqlite:///{db_url}', echo=False)
Session = sessionmaker(bind=engine)
session = Session()
metadata = MetaData(engine)
Base = declarative_base(metadata=metadata)

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'nat_birthrate_2013_2017.sqlite'

In [5]:
# create sqlalchemy class
class BirthRateRecord(Base):
    __tablename__ = 'national_birth_rate_2013_2017'
    
    ID = Column(Integer, primary_key=True)
    Country =  Column(String(255))
    CountryCode = Column(String(255))
    Year = Column(Integer())
    YearCode = Column(Integer())
    Birth = Column(Integer())
    TotalPopulation = Column(Integer())
    BirthRate = Column(Integer())
    AvgAgeOfMother = Column(Integer())
    AvgLMPGestAge = Column(Integer())

In [6]:
# initialize tables in database
metadata.create_all()

In [7]:
# read csv
path = './RawNatalData/Natality_BirthRates_2013_2017.csv'

with open(path, 'r') as csvfile:
    # remove old sqlite file
    data = csv.reader(csvfile);
    header = next(data)
    cleaned = filter(lambda r: r[0] != '' and r[1] != '', data)
    for row in cleaned:
        try:
            record = BirthRateRecord( \
                ID = row[0], \
                Country =  row[1], \
                CountryCode = row[2], \
                Year = row[3], \
                YearCode = row[4], \
                Birth = row[5], \
                TotalPopulation = row[6], \
                BirthRate = row[7], \
                AvgAgeOfMother = row[7], \
                AvgLMPGestAge = row[8]
            )
            session.add(record)
        except ex:
            print(list(row))
    session.commit()

In [8]:
# check data in db
query = session.query(BirthRateRecord)

df = pd.read_sql(query.statement, query.session.bind)

df

,ID,Country,CountryCode,Year,YearCode,Birth,TotalPopulation,BirthRate,AvgAgeOfMother,AvgLMPGestAge
0,1,"Baldwin County, AL",1003,2013,2013,2160,195540,11.05,11.05,27.31
1,2,"Baldwin County, AL",1003,2014,2014,2244,200111,11.21,11.21,27.48
2,3,"Baldwin County, AL",1003,2015,2015,2344,203709,11.51,11.51,27.53
3,4,"Baldwin County, AL",1003,2016,2016,2247,208563,10.77,10.77,27.72
4,5,"Baldwin County, AL",1003,2017,2017,2322,212628,10.92,10.92,27.96
5,6,"Calhoun County, AL",1015,2013,2013,1347,116736,11.54,11.54,25.91
6,7,"Calhoun County, AL",1015,2014,2014,1291,115916,11.14,11.14,26.13
7,8,"Calhoun County, AL",1015,2015,2015,1400,115620,12.11,12.11,26.27
8,9,"Calhoun County, AL",1015,2016,2016,1357,114611,11.84,11.84,26.46
9,10,"Calhoun County, AL",1015,2017,2017,1338,114728,11.66,11.66,26.46
10,11,"Etowah County, AL",1055,2013,2013,1182,103931,11.37,11.37,25.85
11,12,"Etowah County, AL",1055,2014,2014,1159,103531,11.19,11.19,25.96
12,13,"Etowah County, AL",1055,2015,2015,1214,103057,11.78,11.78,25.80
13,14,"Etowah County, AL",1055,2016,2016,1214,102564,11.84,11.84,26.33
14,15,"Etowah County, AL",1055,2017,2017,1213,102755,11.80,11.80,26.29
15,16,"Houston County, AL",1069,2014,2014,1303,104193,12.51,12.51,26.65
16,17,"Houston County, AL",1069,2015,2015,1294,104173,12.42,12.42,26.91
17,18,"Houston County, AL",1069,2016,2016,1333,104056,12.81,12.81,26.95
18,19,"Houston County, AL",1069,2017,2017,1295,104346,12.41,12.41,26.82
19,20,"Jefferson County, AL",1073,2013,2013,8640,659479,13.10,13.10,27.48
20,21,"Jefferson County, AL",1073,2014,2014,8925,660793,13.51,13.51,27.75
21,22,"Jefferson County, AL",1073,2015,2015,8792,660367,13.31,13.31,27.95
22,23,"Jefferson County, AL",1073,2016,2016,8655,659521,13.12,13.12,28.12
23,24,"Jefferson County, AL",1073,2017,2017,8706,659197,13.21,13.21,28.32
24,25,"Lee County, AL",1081,2013,2013,1858,150933,12.31,12.31,27.15
25,26,"Lee County, AL",1081,2014,2014,1890,154255,12.25,12.25,27.63
26,27,"Lee County, AL",1081,2015,2015,1988,156993,12.66,12.66,27.83
27,28,"Lee County, AL",1081,2016,2016,1898,158991,11.94,11.94,27.94
28,29,"Lee County, AL",1081,2017,2017,1898,161604,11.74,11.74,28.10
29,30,"Madison County, AL",1089,2013,2013,4106,346892,11.84,11.84,27.71
...,...,...,...,...,...,...,...,...,...,...
3046,3047,"Sheboygan County, WI",55117,2017,2017,1204,115344,10.44,10.44,28.44
3047,3048,"Walworth County, WI",55127,2014,2014,1072,103527,10.35,10.35,28.52
3048,3049,"Walworth County, WI",55127,2015,2015,1055,102804,10.26,10.26,28.64
3049,3050,"Walworth County, WI",55127,2016,2016,967,102959,9.39,9.39,28.85
3050,3051,"Walworth County, WI",55127,2017,2017,917,103082,8.90,8.90,29.16
3051,3052,"Washington County, WI",55131,2013,2013,1343,132739,10.12,10.12,29.75
3052,3053,"Washington County, WI",55131,2014,2014,1332,133251,10.00,10.00,29.64
3053,3054,"Washington County, WI",55131,2015,2015,1381,133674,10.33,10.33,29.60
3054,3055,"Washington County, WI",55131,2016,2016,1331,134296,9.91,9.91,29.87
3055,3056,"Washington County, WI",55131,2017,2017,1291,135101,9.56,9.56,30.21
3056,3057,"Waukesha County, WI",55133,2013,2013,3697,393843,9.39,9.39,30.23
3057,3058,"Waukesha County, WI",55133,2014,2014,3885,395118,9.83,9.83,30.34
3058,3059,"Waukesha County, WI",55133,2015,2015,3703,396488,9.34,9.34,30.69
3059,3060,"Waukesha County, WI",55133,2016,2016,4008,398424,10.06,10.06,30.77
3060,3061,"Waukesha County, WI",55133,2017,2017,3863,400621,9.64,9.64,31.08
3061,3062,"Winnebago County, WI",55139,2013,2013,1859,169541,10.96,10.96,28.21
3062,3063,"Winnebago County, WI",55139,2014,2014,1826,169511,10.77,10.77,28.39
3063,3064,"Winnebago County, WI",55139,2015,2015,1916,169546,11.30,11.30,28.71
3064,3065,"Winnebago County, WI",55139,2016,2016,1905,169886,11.21,11.21,28.75
3065,3066,"Winnebago County, WI",55139,2017,2017,1833,170414,10.76,10.76,28.88
3066,3067,"Unidentified Counties, WI",55999,2013,2013,23647,2255109,10.49,10.49,28.12
3067,3068,"Unidentified Counties, WI",55999,2014,2014,21679,2049532,10.58,10.58,28.24
3068,3069,"Unidentified Counties, WI",55999,2015,2015,21579,2048897,10.53,10.53,28.43
3069,3070,"Unidentified Counties, WI",55999,2016,2016,21572,2049256,10.53,10.53,28.57
3070,3071,"Unidentified Counties, WI",55999,2017,2017,21252,2050854,10.36,10.36,28.71
3071,3072,"Unidentified Counties, WY",56999,2013,2013,7644,582658,13.12,13.12,27.09
3072,3073,"Unidentified Counties, WY",56999,2014,2014,7696,584153,13.17,13.17,27.19
3073,3074,"Unidentified Counties, WY",56999,2015,2015,7765,586107,13.25,13.25,27.47
3074,3075,"Unidentified Counties, WY",56999,2016,2016,7386,585501,12.61,12.61,27.75
3075,3076,"Unidentified Counties, WY",56999,2017,2017,6903,579315,11.92,11.92,27.87